### ISSUE TITLE
Have an indicator that says whether you can talk or not

### ISSUE THREAD

**Issue by banool** [banool/team_heist_tactics#102]
We toggle this on when:
- No one has made a move yet.
- Someone stands on a green doorway and places a tile (if that feature is on).
- Someone stands on a timer.

We toggle this off when:
- Someone moves.

**Comment by kemcbride** [comment]
should the server know about talking rules at all?

part of me wants to say "yes", but another part of me wants to say "no"
"yes" - because it's a core game rule and would need to be controlled by the server (eg. it registers officially when someone has moved, etc)

"no" - because it has no impact on the implementation of the game or its logic. (except for timer flip. but really, it doesn't even affect that)

**Comment by banool** [comment]
I think it's hard for the frontend to figure out. Like when you step on a timer, the frontend has no idea that that is anything special, so the server needs to tell it, much like with the timer flip. The same is true for when we have green doorway thingos.

**Comment by kemcbride** [comment]
Daniel did this so - 441b67be5a6942d98b36a8179652529b116a25d1

Via more commits thant hat, but we can call this done.
