### ISSUE TITLE
Render 'X' over used timers in UI

### ISSUE THREAD

**Issue by kemcbride** [banool/team_heist_tactics#152]
What I suspect is needed...
timer component already updates with the time from the server, 

so I expect all that's needed on the UI side for timer flip is to add an "X" over any timers that have been flipped.
I'm not sure how you will want to keep track of that.

The server _could_ provide game_state.flipped_timers  = MapPosition[], game_state.crushed_cameras = MapPosition[]
that way, the UI could just render Xs on those given map positions? otherwise it might be tricky for the UI to keep track of that.

**Comment by banool** [comment]
The server should just alter the type of the square. In my ever-re-proven foresight, I included a square type for it in the initial protobuf definitions:
```
SquareType.TIMER_FLIP_USED
```

**Comment by kemcbride** [comment]
the server does alter the type of square!

but how does the UI know to render a square differently? it just renders tiles

**Comment by banool** [comment]
Depends on what we wanna do with the squares. Currently the UI gets them, so it could just go through all the squares and find the squares of that type, figure out their map position (easy) and then render crosses. But if we wanna make the UI stop receiving this information (because it doesn't need it except for the crosses) and instead get more specific information, we could do that too.

**Comment by kemcbride** [comment]
like the UI only gets the tile names + rotations + positions?

and it could be a separate list similar to possible_placements? crossed_out_squares?

**Comment by banool** [comment]
Implemented with https://github.com/banool/team_heist_tactics/commit/cf463bed7a40a5569fea1001aacb07b0f1e910ad.
