### ISSUE TITLE
Make it that once you place a tile, the possible placement square is no longer considered a valid option

### ISSUE THREAD

**Issue by banool** [banool/team_heist_tactics#26]

**Comment by kemcbride** [comment]
This item is pretty related to https://github.com/banool/team_heist_tactics/issues/29
- the issue (I think) is that the code still sees the original "{Color}Door" wall as a potential entry point for new tile placement.

Once issue 29 is done, (aka, the wall is modified to be clear instead of {Color}Door), this *should* also be resolved.
