### ISSUE TITLE
Fix the canvasPositionToMapPosition function

### ISSUE THREAD

**Issue by banool** [banool/team_heist_tactics#28]
Currently this function only really works well close to the center of the map. The further out you get, the more inaccurate the conversion back from canvas position to map position becomes.

**Comment by kemcbride** [comment]
This issue is really big....

I think as of now, we have 2 problems:
* Tile Placement (#61) - sometimes, Tiles are placed at a strange offset. Somehow, they are still continuously placed touching each other, but with an incorrect offset, which results in it appearing that heisters are moving in random locations on tile tiles, that do not correspond to the tile's squares & walls.

* Heister Position (#??) - when heisters move into new tiles, and often when they are moving within non-center tiles (any tile that is not 0,0 or tile1a) if they pass a square that is a multiple of 4 (ie. would contain a wall if the tiles were exactly adjacent), they move "twice the amount" (where twice the amount is actually INTERNAL_SQUARE_SIZE + 2 * INTERNAL_TILE_OFFSET) (*note: I am not 100% this is what is happening, but I'm pretty confident that it's what is happening)

**Comment by kemcbride** [comment]
For heister position, I think we've kind of informally agreed that it's much easier to solve these separately.

If we can solve the problem of Tile Placement (finding the top-left corner of a Tile at map pos (x, y) in terms of pixels on the canvas, then we can solve the problem of Heister Position by calculating first which tile it's on, and secondly calculating its square offset within that tile.

**Comment by banool** [comment]
Just to keep this updated, the latest intuition is that we should be using a tree of sorts. More concretely, we should be placing each tile relative to its parent tile, instead of trying to place them all absolutely.

**Comment by fboxwala** [comment]
Dmitry's solution: 
'''
So a tile R right-moves and U up-moves away from the start will be at the server coordinates:
X = 4R + U
Y = 4U - R
Solve:
https://www.wolframalpha.com/input/?i=solve+for+U%2CR%3A+Y+%3D+4U+%2B+R%2C+X+%3D+4R+-+U
U = (4Y + X)/17
R = (4X - Y)/17

The client coordinates also add twice the margin m when you go up/right, so you have:
X' = R*(2m + 4) + U = X + 2mR
Y' = U*(2m + 4) - R = Y + 2mU

X' = X + 2m(4X - Y)/17
Y' = Y + 2m(4Y + X)/17
'''
Recursive solution: always start from 0,0, recurse through neighbours (that exist) to find the parent of the tile you want to place, place the tile relative to the parent.
